### ISSUE TITLE
I, for one, welcome our new black over-headers. 

### ISSUE THREAD

**Issue by obsidience** [DennisSnijder/MakeGithubGreatAgain#11]
Oh, back to the issue.  It looks like someone sneezed on your camera lens.  

Reproduce steps:
- Visit: https://github.com/DennisSnijder/MakeGithubGreatAgain
- Notice boogers all over the image.  Gnarly.

I'd produce logs but my deep machine learning neural net on booger detection is in it's infancy.  It keeps detecting a tree...

**Comment by DennisSnijder** [comment]
Issue way too complex, crashed Gitlab servers.
Wontfix
