### ISSUE TITLE
Define downloadURL and updateURL in userscript for auto-updating

### ISSUE THREAD

**Issue by Daiz** [DennisSnijder/MakeGithubGreatAgain#13]
https://wiki.greasespot.net/Metadata_Block#.40downloadURL
https://wiki.greasespot.net/Metadata_Block#.40updateURL

Would probably also be a good idea to make a tag like `stable` and then point to the raw .user.js URL in said tag (eg. `https://github.com/DennisSnijder/MakeGithubGreatAgain/raw/stable/MakeGithubGreatAgain.user.js`) and then update the tag whenever making a new release and bumping the version.

**Comment by DennisSnijder** [comment]
Feel free to create a PR for this.
