### ISSUE TITLE
Would love a Safari extension 🥂

### ISSUE THREAD

**Issue by LinusU** [DennisSnijder/MakeGithubGreatAgain#17]
The javascript seems to work great in Safari as well, would be nice with a packaged extension :)

**Comment by auduchinok** [comment]
@LinusU How do you load it in Safari? I've tried some extensions for that years ago, but can't remember which worked better.

**Comment by DennisSnijder** [comment]
@auduchinok Make sure you have developer mode enabled in Safari.
After that go to the developer menu and open Extension builder.
Import the extension from the repository, install it and you are good to go! 👍

**Comment by LinusU** [comment]
Amazing 😍

**Comment by cooper** [comment]
Is there any way to use it without having to "install" it every time I open Safari?
<img width="812" alt="screen shot 2017-02-12 at 12 45 36 am" src="https://cloud.githubusercontent.com/assets/323847/22859959/a3841262-f0bc-11e6-87c5-cbfec8c5a7e6.png">

**Comment by ngyikp** [comment]
@cooper - The install dialog did say "Without a Safari Extensions Certificate, this extension will only be available until you quit Safari".

That certificate is part of the Apple Developer Program and costs USD99 per year. Alternatively, someone that is already enrolled could sign and distribute a `.safariextz` for everyone to use.

**Comment by ayazhafiz** [comment]
Here's a signed one! Enjoy!
(zipped b/c Github won't let me upload .safariextz in issues 😢 )
[MakeGithubGreatAgain.safariextz.zip](https://github.com/DennisSnijder/MakeGithubGreatAgain/files/769869/MakeGithubGreatAgain.safariextz.zip)

**Comment by AnishGDev** [comment]
Yeah I have a similar problem. Since I don't have a Apple Developer account I can't package my safari extension, Procrastube.

Would be great if you could help out @ayazhafiz
