### ISSUE TITLE
Read my browsing history?

### ISSUE THREAD

**Issue by GuardRex** [DennisSnijder/MakeGithubGreatAgain#26]
![capture](https://cloud.githubusercontent.com/assets/1622880/22864020/0a5f680e-f10f-11e6-8143-a17d79bbc848.PNG)

Why does the extension need to read the user's browsing history?

**Comment by DennisSnijder** [comment]
On an older version we accidently requested for browser history permissions.
If you look trough the code in the repository nothing is being read from your browser history. Soon there will be an chrome extension update.
