### ISSUE TITLE
New release to chrome store

### ISSUE THREAD

**Issue by audiolion** [DennisSnijder/MakeGithubGreatAgain#28]
Hey could you push the 1.3.0 release to the chrome store? My body is ready for teh faster switching 😋

**Comment by DennisSnijder** [comment]
Yes, will do that in a bit. Thanks for reminding me 👍

**Comment by kinncj** [comment]
Your item is in the process of being published and may take up to 60 minutes to appear in the Chrome Web Store. 

Thanks.

**Comment by vaygr** [comment]
Just letting you know that new release `1.3.0` has just made toolbar button disappear and also made the extension dysfunctional on Vivaldi `1.7 stable channel` under Linux.

Version `1.2.1` worked fine (but with flickering issue).

**Comment by kinncj** [comment]
![kapture 2017-02-13 at 12 14 45](https://cloud.githubusercontent.com/assets/292542/22894168/133f0af6-f1e6-11e6-952d-aee121f272fc.gif)

Are you using the chrome-store version?

1. If yes
    1. What chrome version?
2. If not
    1. This is due to the 2 manifest files
        1. https://github.com/DennisSnijder/MakeGithubGreatAgain/blob/master/FireFox/manifest.json
        2. https://github.com/DennisSnijder/MakeGithubGreatAgain/blob/master/manifest.json

**Comment by vaygr** [comment]
Yeah, chrome-store version, which got updated just an hour ago.

Vivaldi `1.7.735.46` uses Chrome `56.0.2924.88`.

**Comment by vaygr** [comment]
Hmm, sounds like a false alarm guys.

The button has been actually moved into address bar with "turned off" mode by default. I re-enabled it, and now everything seems to be fine.

![shot-2017-02-13_1384](https://cloud.githubusercontent.com/assets/8810597/22894841/71d0a3de-f1e8-11e6-8787-0a7e071e5817.png)
