### ISSUE TITLE
header-dark removing no long works

### ISSUE THREAD

**Issue by DennisSnijder** [DennisSnijder/MakeGithubGreatAgain#31]
Github just updated the `header-dark` class to be the default header class.
We need to overwrite the existing CSS class to get the extension working again.

**Comment by KeizerDev** [comment]
Check #27

**Comment by DennisSnijder** [comment]
Added a fix
https://github.com/DennisSnijder/MakeGithubGreatAgain/commit/59cfa7ebef993d0458855ab638de341c9a4844f4

Needs some testing / improvements.

**Comment by Wakeupbuddy** [comment]
Thanks. Please let us know when the new version is pushed to the chrome store.

**Comment by kinncj** [comment]
https://github.com/DennisSnijder/MakeGithubGreatAgain/issues/32#issuecomment-279564015

**Comment by svnpenn** [comment]
https://github.com/DennisSnijder/MakeGithubGreatAgain/issues/34
