### ISSUE TITLE
White text at unfocused search bar in repository scope

### ISSUE THREAD

**Issue by vaygr** [DennisSnijder/MakeGithubGreatAgain#33]
Looks like `div.header-search-scope` also forces `255, 255, 255` for text color.

![shot-2017-02-13_4750](https://cloud.githubusercontent.com/assets/8810597/22909796/3baf327a-f224-11e6-83fd-49198796a4a4.png)

Focused mode is fine though:

![shot-2017-02-13_27868](https://cloud.githubusercontent.com/assets/8810597/22909850/7babcb72-f224-11e6-8f9e-42860204999b.png)

**Comment by RoyalMjz** [comment]
I have also encountered the same problem

**Comment by DennisSnijder** [comment]
Fixed by #38
