### ISSUE TITLE
Looks like Github broke it

### ISSUE THREAD

**Issue by simsketch** [DennisSnijder/MakeGithubGreatAgain#34]
I see the header-dark class toggling, but it looks like they've put the styles into the header class and removed the header-dark class altogether.

**Comment by svnpenn** [comment]
https://github.com/DennisSnijder/MakeGithubGreatAgain/issues/27

**Comment by svnpenn** [comment]
https://github.com/DennisSnijder/MakeGithubGreatAgain/issues/32

**Comment by svnpenn** [comment]
https://github.com/DennisSnijder/MakeGithubGreatAgain/issues/31

**Comment by Viltaria** [comment]
They are evolving...

**Comment by svnpenn** [comment]
@Viltaria yes, they are working very hard to fix stuff that wasnt broken

**Comment by OldManLink** [comment]
Yep, a simple `git pull` fixed it again, thanks guys! 😎

**Comment by simsketch** [comment]
Wow that really is a `.great-header`! :sunglasses:
