### ISSUE TITLE
Enhancement wanted

### ISSUE THREAD

**Issue by iTofu** [DennisSnijder/MakeGithubGreatAgain#41]
See this screenshot:
![4a475a43-7616-4b33-b1e6-b722a5450bfe](https://cloud.githubusercontent.com/assets/10044430/22959121/a5cce9f4-f36e-11e6-9386-d4f9690ce7f0.png)

**Comment by maliming** [comment]
+1

**Comment by 29jitender** [comment]
+1

**Comment by vaygr** [comment]
Same here, it should be fixed by https://github.com/DennisSnijder/MakeGithubGreatAgain/pull/38, but the version in chrome store is outdated. @DennisSnijder should fix that shortly I assume, but for now you can try manual installation as described on the front page cloning repo from master.

**Comment by iTofu** [comment]
@vaygr 
Ye, I see, thank you guy 👍
