### ISSUE TITLE
Add focus class to "This repository" label

### ISSUE THREAD

**Issue by palerdot** [DennisSnijder/MakeGithubGreatAgain#42]
Currently, "This repository" label is blank and white. It is not the default blue bootstrap theme color. When inspected, the label element was missing the **focus** class.

Attached screenshot. At the top left, you can the see the white label without focus.

![missing-focus-class](https://cloud.githubusercontent.com/assets/4299398/22970964/1496f46c-f39a-11e6-9f0a-60c99f847df8.png)

**Comment by vaygr** [comment]
This should be fixed by https://github.com/DennisSnijder/MakeGithubGreatAgain/pull/38, but new version hasn't been pushed to chrome store yet. @DennisSnijder ?

**Comment by DennisSnijder** [comment]
This has been fixed, just do a git pull 👍 
Soon will be published into the chrome extension store.

**Comment by palerdot** [comment]
For some reason, the extension has completely stopped working for me. I'm seeing only the dark header now.

**Comment by jackwilsdon** [comment]
#44 + #45 I think, maybe not pushed to store yet.
