### ISSUE TITLE
Github broke extension again

### ISSUE THREAD

**Issue by nbolt** [DennisSnijder/MakeGithubGreatAgain#44]
Looks like the black bar is back :confused:

**Comment by jackwilsdon** [comment]
It seems to be working fine for me?

**Comment by mscdex** [comment]
I was just about to post this.... it looks like they're now nesting the header. The selector should now be something like `body > div > .header`

**Comment by Andrews54757** [comment]
Its body > div > .header

**Comment by jackwilsdon** [comment]
Would it not be better just making it `.header`, effectively future proofing this from changes in the HTML layout?

**Comment by Andrews54757** [comment]
No. It is not a good practice.

**Comment by Andrews54757** [comment]
However, I think this needs an auto-update system so it will be "unbreakable"

**Comment by nbolt** [comment]
Perhaps an extension option to customize the selector?

**Comment by jackwilsdon** [comment]
I'd say that absolutely referencing the element is not a good practice, as it's better to have ["modular" CSS](http://thesassway.com/intermediate/avoid-nested-selectors-for-more-modular-css) and nothing else on the page has the `.header` class.

**Comment by Andrews54757** [comment]
Or, an auto-update system could be used.

**Comment by jackwilsdon** [comment]
How would that work exactly? The only way you can reliable detect the header is by using the `.header` class (or other classes pertaining to the header), so I don't see why we don't just go for `.header` on it's own.

**Comment by Andrews54757** [comment]
https://developer.chrome.com/extensions/autoupdate

**Comment by jackwilsdon** [comment]
> If you publish using the Chrome Developer Dashboard, you can ignore this page.

And this extension is published using the dashboard, so I don't see what your point is?

**Comment by Andrews54757** [comment]
Yeah, thats true. I forgot

**Comment by Andrews54757** [comment]
Maybe another method to access .header should be used. GitHub could patch the extension by just renaming the class. However, certain things about the header are constant, they dont change.

**Comment by jackwilsdon** [comment]
I doubt they'll rename the `.header` class, it's a sensible name for it. They've kept it when doing the styling changes so I don't see why they'd change it again. I guess you could look it up by it's `banner` role too.

**Comment by Andrews54757** [comment]
Mark Otto seems to be feisty about it though. (https://twitter.com/mdo/status/830138373230653440)

**Comment by jackwilsdon** [comment]
Yeah I get that, but the current class is sensible and hasn't changed even with all of the changes they've implemented.

**Comment by Andrews54757** [comment]
Okay. Also, maybe this project should port to stylus (https://chrome.google.com/webstore/detail/stylus/clngdbkpkpeebahjckkjfobafhncgmne). This is because GitHub is going to change more stuff that we might not like, and it would be harder for this project if it is a standalone extension.

**Comment by Andrews54757** [comment]
https://github.com/StylishThemes/GitHub-Dark uses it

**Comment by DennisSnijder** [comment]
Fixed now, chrome extension store update coming soon!
