### ISSUE TITLE
Colors are weird

### ISSUE THREAD

**Issue by Viltaria** [DennisSnijder/MakeGithubGreatAgain#56]
Looks like Github changed their styling

**Comment by Viltaria** [comment]
https://gyazo.com/1e1c1f8302f5c732f99c99bc36fc7c5c

**Comment by bntzio** [comment]
Yeah this is happening to me as well, looks like Github changed its css.

**Comment by bntzio** [comment]
Just dropped in a pull request to fix this (#57) 👍 @Viltaria @DennisSnijder

**Comment by Viltaria** [comment]
The hero we need! @bntzio

**Comment by bntzio** [comment]
If someone needs to fix the issue before @DennisSnijder do the merge you guys can download my fork and go to `chrome://extensions` then click *Load unpacked extension* and select the fork folder.

Here's the fork 👉 https://github.com/bntzio/MakeGithubGreatAgain

**Comment by PuKoren** [comment]
Thanks @bntzio it is working fine. However I have a small display issue on the Pull Request/Issues views:

![pull requests](https://user-images.githubusercontent.com/4202557/28661411-cf82ce18-72b6-11e7-879d-df8f6dfab430.png)

As you can see its not very readable. Maybe something else changed with the latest GitHub update?

**Comment by bntzio** [comment]
@PuKoren Are you using some chrome extension to change the GitHub layout apart from `MakeGithubGreatAgain`?

I can see a **ToDo** link in the screenshot. Maybe that's the styling conflict.

**Comment by PuKoren** [comment]
True, I use ZenHub. I just tried to disable it and still see the white color when on Pull Requests / Issues views.

You don't have the same issue?

**Comment by bntzio** [comment]
Nope, have u tried closing your browser and re-opening? or maybe delete the cache

**Comment by PuKoren** [comment]
Ok then I guess you are right, thanks

**Comment by bntzio** [comment]
I suggest you download [Chrome Canary](https://www.google.com/chrome/browser/canary.html), install the extension manually again and go to https://github.com again to see if it solves the issue, if yes, then there's a conflicting extension messing with `MakeGithubGreatAgain` in your normal Chrome browser.

**Comment by DennisSnijder** [comment]
Should be fixed now thanks to #62
