### ISSUE TITLE
Appoint a new director of mergifications

### ISSUE THREAD

**Issue by joeytwiddle** [DennisSnijder/MakeGithubGreatAgain#59]
Often Github's changes to CSS can break extensions like this one, but sometimes contributors will come out with a fix pretty soon.

It would be great to have someone who could quickly merge these kinds of fixes, so that users don't suffer a period of lost functionality.

However I appreciate it might be a little bit complicated, because the extension would also need to be pushed up to the Chrome Web Store.

I have no idea what is involved in that, or whether it is a task that can be easily shared. But if it could, that would be great!

*PS: This issue's title was a short-lived topical reference.*

**Comment by DennisSnijder** [comment]
hey @joeytwiddle I already mailed you a while ago about the opportunity for you to become a maintainer, also back when i released the chrome plugin someone else hosted it for me.. (Pretty hard to reach him)

**Comment by kinncj** [comment]
Not hard at all, as long as you do reach me :-)

**Comment by DennisSnijder** [comment]
@kinncj Awesome! Didn't know that was you :)

**Comment by kinncj** [comment]
:-)

**Comment by joeytwiddle** [comment]
Ah so you did! Sorry I missed it. Will be in touch...
