### ISSUE TITLE
Put the list of repos back on the right again?

### ISSUE THREAD

**Issue by joeytwiddle** [DennisSnijder/MakeGithubGreatAgain#67]
Recently, the box on the dashboard containing the list of your repos has moved from the right of the page to the left of the page.

Things being as they are these days, I am not really against things moving from the right to the left.

But if enough people are bothered by this, I don't mind adding a `float: right` to restore things back how they were in 2016.

:+1: = move those repos back over to the right. Restore balance to the desktop.
:-1: = keep the repos where they are now. Keep those Github designers in a job.

This offer will expire 31st October 2018.

**Comment by MattRyder** [comment]
Yeah, +1 for this.

The one thing that annoys me, isn't the left-alignment, but the fact that it's gone from discrete rows with the pale yellow 'private tint' to a mis-mashed list.

But rolling it all back would be welcomed.
I'd offer to help but I do back-end mostly, I'd end up making it all much, much worse.

**Comment by joeytwiddle** [comment]
I was thinking to add this fix if it got 5 upvotes. (It's only actually a tiny bit of CSS.) It looks like it's been done in the open PR actually.

But there might be a problem on the horizon. GitHub has a new "dashboard" feature, currently in beta testing, which had a left and a right sidebar. (I found I could opt in from the [front page](https://github.com/).)

If that layout becomes the default at some point, we might want to reconsider how to stay "traditional" whilst also enjoying new features.
