### ISSUE TITLE
Add the ability to switch between white and dark themes

### ISSUE THREAD

**Issue by wudifeixue** [DennisSnijder/MakeGithubGreatAgain#8]
Hi again, I think it would be a pretty nice feature if we can switch the theme black and white by click on the extension icon.

**Comment by renatomefi** [comment]
@wudifeixue Would be awesome if you could send a PR for that!

**Comment by Crecket** [comment]
I'll send a pull request in a bit, give me a few mins

**Comment by Crecket** [comment]
#12
